config/routes.rb
Rails.application.routes.draw do

  get 'auth/github/callback', to: 'sessions#github_auth'
  get 'auth/google_oauth2/callback', to: 'sessions#google_auth'
  
  get 'auth/failure', to: 'sessions#new'

  #signup
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/profile', to: 'users#profile'

  resources :users, only: [:index, :show] do
    resources :lists, only: [:show]
  end
  #sessions routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources:lists do
    resources :tasks
    resources :comments
  end
  
  root to: 'sessions#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :user
    belongs_to :list

    validates :content, presence: true

end

app/models/list.rb
class List < ApplicationRecord

    belongs_to :user
    has_many :comments
    has_many :commentators, through: :comments, source: 'user'
    has_many :tasks, dependent: :destroy

    validates_presence_of :name, uniqueness: true

    accepts_nested_attributes_for :tasks

    scope :ordered_by_name, -> { reorder(name: "ASC")}
end

app/models/task.rb
class Task < ApplicationRecord

    belongs_to :list

    validates_presence_of :name

end

app/models/user.rb
class User < ApplicationRecord
    
    has_secure_password
    has_many :lists
    has_many :comments
    has_many :commented_lists, through: :comments, source: :list
    
    has_many :tasks, through: :lists

    validates :username, length: { minimum: 2 }
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :password, length: { in: 4..20 }

    def self.find_or_create_from_omniauth_hash(auth)
      # Creates a new user only if it doesn't exist
      email = auth[:info][:email]
      # binding.pry
      find_or_create_by(email: email) do |user|
          user.provider = auth.provider
          user.username = auth.info.name
          user.email = auth.info.email
          user.password = SecureRandom.hex(10)
      end
    end

    def self.all_except(user)
      where.not(id: user)
    end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user, :logged_in?, :authenticate_user!
    
    private

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!current_user
    end

    def authenticate_user!
        redirect_to login_path if !logged_in?
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @list = List.find(params[:list_id])
        comment = Comment.new(comment_params)
        comment.list = @list
        comment.user = current_user
        comment.save
        redirect_to user_list_path(@list.user, @list)
    end

    private

    def comment_params
        params.require(:comment).permit(:content)
    end
end 

app/controllers/lists_controller.rb
class ListsController < ApplicationController

    def index
        if logged_in?
            @lists = current_user.lists.ordered_by_name
        else
            redirect_to login_path
        end
    end

    def show
    
       if params[:user_id].present?
        @user = User.find(params[:user_id])
        @list = @user.lists.find(params[:id])
       else
        @list = current_user.lists.find(params[:id])
       end
       
    end
    
    def new 
        if logged_in?
            @list = current_user.lists.build
        else
            redirect_to login_path
        end
    end
    
    def create
        @list = current_user.lists.build(list_params)
        if @list.save
            redirect_to lists_path(@list)
        else
          render :new
        end
    end

    def edit
        @list = current_user.lists.find(params[:id])
    end

    def update
        @list = List.find(params[:id])
        @list.update(list_params)
        redirect_to lists_path(@list)
    end

    def destroy
        @list = List.find(params[:id])
        @list.destroy
        redirect_to lists_path
    end
    
    private
    
    def list_params
        params.require(:list).permit(:name, tasks_attributes: [:name, :summary, :description, :priority, :created_by, :project, :status])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    helper_method :logged_in?, :current_user

    def new
      if logged_in?
        redirect_to profile_path(current_user)
      else
        @user = User.new
      end
    end

    def create
      @user = User.find_by(:email => params[:session][:email])

      if @user && @user.authenticate(params[:session][:password])

        session[:user_id] = @user.id
        flash[:notice] = "#{@user.username} has successfully logged in!"
        redirect_to profile_path(@user)
      else
        flash[:alert] = "Sorry your email or password was invalid"
        redirect_to login_path
      end
    end

    def destroy
      if logged_in? 
        session.clear 
        flash[:notice] = "Signed out successfully"
        redirect_to login_path
      else
        redirect_to signup_path
      end
    end

    def google_auth

      @user = User.find_or_create_from_omniauth_hash(auth)
  
      session[:user_id] = @user.id
      redirect_to profile_path, notice: 'Successfully connected to Google!'
    end

    def github_auth
      
      @user = User.find_or_create_from_omniauth_hash(auth)
      # binding.pry
      session[:user_id] = @user.id
      redirect_to profile_path, notice: 'Successfully connected to Github!'
    end
  
    private
  
    def auth
      request.env['omniauth.auth']
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    before_action :current_user, :logged_in?

    def index

    end

    def new
        @list = List.find(params[:list_id])
        @task = @list.tasks.build
    end

    def create
        @list = List.find(params[:list_id])
        @task = @list.tasks.build(task_params)
        if @task.save
          redirect_to list_path(@list)
        else
          flash[:notice] = "Error"
          render 'new'
        end
    end

    def edit        
        @list = List.find(params[:list_id])
        puts @list.id
        @task = Task.find(params[:id])
    end

    def update
        @list = List.find(params[:list_id])
        @task = Task.find(params[:id])
        @task.update(task_params)
        redirect_to list_path(@list)
    end

    def destroy
        @list = List.find(params[:list_id])
        @task = @list.tasks.find_by(params[:id])
        @task.destroy
        redirect_to list_path(@list)
    end
  
    private

    def task_params
        params.require(:task).permit(:name, :summary, :description, :priority, :created_by, :project, :status)
    end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in?, except: [:show]

  def index
    @users = User.all_except(current_user)
  end

  def new
    if logged_in?
      redirect_to profile_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Signed in successfully as #{@user.username}"
      redirect_to profile_path(@user)
    else
      flash[:alert] = "#{@user.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def profile
    @user = User.find_by(id: session[:id])
  end

  private

  def user_params 
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  module SessionsHelper

  end
end

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>
    <% f.text.field :comment, placeholder: "Comment", class: "form-control" %>
    <br>
    <p><%= link_to 'Delete', list_comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>

app/views/comments/index.html.erb
<h1>See what Comments your co workers are posting!</h1>
<br>
<h3>Comments</h3>

app/views/comments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-12 bg-white">
      <h1 class="text-center log-in">Add a Comment</h1>
      <%= render 'form' %>
      <br>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Maintenaceco</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= stylesheet_pack_tag 'application' %>
    </head>

  <body>
      <%= render 'partials/jumbotron' %>
      <%= render "partials/alerts" %>

      <%if logged_in?%>
      <%= render "partials/nav" %>
      <%end%>

      <main role="main">
      <div class="container">
    <%= yield %>
      <hr>
      </div>
  </body>
  <%= render 'partials/footer' %>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% @list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name, placeholder: "Name", class: "form-control"%>

  <%= f.fields_for :task_attributes do |task| %>

  <%#= task.text_field :name, placeholder:"Client's Name", class: "form-control" %>
  <p><span class="task-list-text complete-text">Complete?   
  </span><%= task.check_box :status %></p>
  
  <% end %>

  <%= f.submit class: "btn btn-outline-success" %>
<% end %>

app/views/lists/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">

      <h1 class="text-center log-in">Edit Your List</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<h2><ul> Welcome, <%= current_user.username if !current_user.nil? %></ul></h2>

<center>
  <div class="container">
    <div class="col-sm-2">
      <h1 class="log-in text-center">Task List</h1>
      <% @lists.each do |list| %>
        <ul class="list-index-container">
          <p class="task-list-text display-inline"><%= list.name %></p>
          <h6>List
          <p class="task-list-text display-inline"><%= list.id %></p>

            <div role="group" aria-label="...">
              <%= button_to "View Tasks", list_path(list), method: 'get', class: "btn btn-outline-success"%><br>
              <%= button_to "Edit", edit_list_path(list), method: 'get', class: "btn btn-outline-warning"%><br>
              <%= button_to "Delete", list_path(list), method: 'delete', class: "btn btn-outline-danger"%><br>
            </div>
        </ul>
      <% end %>
    </div>
  </div>
</center>

    

app/views/lists/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1 class="text-center log-in">Create Your List</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>


app/views/lists/show.html.erb
<div class="container">
<div>

<div class="col-sm-12">
<h1 class="log-in text-center"><%= @list.name %></h1>
        <hr>
        <p><span>Tasks</span></p>
        
        <% @list.tasks.each do |task| %>
          <div class="task-container">
          <ul>
          <h6 style="float::left;">Client</h6>
              <p class="task-list-text display-inline"><%= task.name %></p>
              
              <h6 style="float::left">Project</h6>
              <p><%= task.project %></p>
              <h6 style="float::right">Summary</h6>
              <p><%= task.summary %></p>

              <div style="float::right">
              <p>Completed ?</p>
              <p class="float::right"><%= check_box_tag 'completed?', 1, task.status, disabled: true, id: "task_complete" %></p>
              </div>

              <div role="group" aria-label="...">
                <% if !@user %>
                <%= button_to "Edit", edit_list_task_path(@list,task), method: 'get', class: "btn btn-outline-warning"%>
                <br>
                <%= button_to "Delete", list_task_path(@list,task), method: 'delete', class: "btn btn-outline-danger"%>
                <% end %>
                </div>
          </ul>
          </div>
          <% end %>
       
          <% if !@user %>
          <br>
          <%= link_to "New Task", new_list_task_path(@list), method: 'get', class: "btn btn-outline-success"%>
          <% end %>
          
          </div>
          <br>
          <div class="comments">
          <h3>All Comments</h3>
          <ul>
          <% @list.comments.each do |comment| %>
            <li>
            <%= comment.content %>
            From: <%= comment.user.username %>
            </li>
            <% end %>
            </ul>
            </div>
            <div class="new_comment">
            <h3> Add Comment </h3>
            
            <%= form_with model: [@list, Comment.new], local: true do |form| %>
              <%= form.label :comment %>
            <%= form.text_field :content %>
          <% end %>

      </div>
    </div>
</div>

app/views/partials/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/partials/_footer.html.erb
<footer>
<p>&copy; MaintenanceCo 2020</p>
</footer>

app/views/partials/_jumbotron.html.erb
<div class="jumbotron jumbotron-fluid">
  # <div class="container">
    <center class="logo"><%= image_tag 'LogoMakr-8ezZYq.png', style: 'height:20%; width:20%' %></center>
    <br>
    <center><h1 class="display-4">MaintenanceCo - The Repair Task Tracker</h1>
    
    <p class="lead">The industry leader for helping Maintenance and Repair workers keep track of their jobs on properties.</p> 
    </center>
</div>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand">
    <%= image_tag 'LogoMakr-8ezZYq.png', style: 'height:10%; width:10%' %>
  </a>


  <div>
    <ul class="nav navbar-nav">
      <li>
        <%= link_to "Profile", profile_path(current_user) %>
      </li>
      &nbsp;
      &nbsp;
      <li>
        <%= link_to "View Lists", lists_path %>
      </li>
      &nbsp;
      &nbsp;
      <li>
        <%= link_to "Create New List", new_list_path %>
      </li>
      &nbsp;
      &nbsp;
      <li>
        <%= link_to "Collegues", users_path %>
      </li>
      &nbsp;
      &nbsp;
      <li>
        <%= link_to "Logout", logout_path, method: "delete" %>
      </li>
    </ul>
  </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_for ([@list, @task]) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "Fields are blank, Please input data") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br><%= f.label :name %>
  <br><%= f.text_field :name, placeholder: "Name", class: "form-control" %>
  <br>
  <p><span class="task-list-text complete-text">Complete?   </span><%= f.check_box :status %></p>
  <br><%= f.label :project %>
  <%= f.number_field :project, {min:1, max:1000}%><br>

  <br><%= f.label :priority%><br>
  <%= f.select :priority, ['Low','Medium','High']%><br>

  <br><%= f.label :summary%><br>
  <%= f.text_field :summary%><br>
  
  <br><%= f.label :description%><br>
  <%= f.text_area :description%><br>
  <br>
  <%= f.submit class: "btn btn-outline-success" %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
    
      <h1 class="text-center log-in">Edit Your Task</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">

      <h1 class="text-center log-in">Create Your Task</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="col-sm-12">
    <center>
        <table>
            <tr>
                <th><h2>Co Workers</h2></th>
            <tr>
            <% @users.each do |user| %>
            <tr>
                <td><%= link_to user.username, user %></td>
            </tr>
            <% end %>
        </table>
    </center>
</div>

app/views/users/new.html.erb
<div class="form_fields">
    <center>
        <h1> Register to MaintenanceCo </h1>
    <h6> Already have an account? &nbsp  
        <%= link_to "Sign In", login_path%>
    </h6>
    <br>

      
        <%= form_for(@user, url: signup_path) do |f| %>
            
            <%= f.label :username %>
            <%= f.text_field :username %><br><br>
            
            <%= f.label :email %>
            <%= f.email_field :email %> <br><br>
            
            <%= f.label :password %>
            <%= f.password_field :password %><br><br>
        
            
            <h6> ** All field musts be filled out. </h6><br>
            
            <%= f.submit "Create Account" %><br><br>

        <% end %>
    <p> or </p>
    <h6> 
        <%= link_to 'Sign Up with Gmail', 'auth/google_oauth2/'%>
        <br><br>
        <%= image_tag 'Gmail.png', style: 'height:5%; width:5%'%>
        <br><br>
        <%= link_to 'Sign Up with Github', 'auth/github/'%>
        <br><br>
        <%= image_tag 'Github.png', style: 'height:5%; width:5%'%>
    </h6>
    <br>
    </center>
</div>

app/views/users/profile.html.erb
<center><h1>Welcome <%=current_user.username %></h1> <br>
<p>Get started by creating your lists in the Create List section!</p>
<br>
<br></center>

app/views/users/show.html.erb
<div class="col-sm-12">
    <table>
        <tr>
            <th><%= @user.username %> Lists</th>
        <tr>
            <% @user.lists.each do |list| %>
            <tr>
                <td><%= link_to list.name, user_list_path(@user, list) %></td>
            <tr>
            <% end %>
    </table>
</div>